v2.0

diff --git a/blog-handler b/blog-handler
--- a/blog-handler
+++ b/blog-handler
@@ -10,7 +10,8 @@
 name="R. Nicolás Savinelli"
 webdir="$PWD"
 website="https://rnsavinelli.github.io/" # Keep a trailing slash.
-css="../css/stylesheet.css"
+css="../css/bootstrap.min.css" # Bare in mind that the .entry class should be declared in this file.
+standalonecss="../css/stylesheet.css"
 blogfile="blog.html"
 blogindexfile="blogindex.html"
 websiteindexfile="index.html"
@@ -29,7 +30,7 @@ fi
 
 _usageinfo() {
      printf \
-        "blog-handler v1.3 Blogs and RSS feeds in less than 150 lines of shell script.\\nCopyright (c) 2018-2020 Luke Smith <luke@lukesmith.xyz>.\\nCopyright (c) 2018-2020 The lb contributors.\\nCopyright (c) 2020 R Nicolás Savinelli <rsavinelli@est.frba.utn.edu.ar>.\\n\\nUsage: blog-handler [OPTION]\\n\\n\
+        "blog-handler v2.0 Blogs and RSS feeds in less than 150 lines of shell script.\\nCopyright (c) 2018-2020 Luke Smith <luke@lukesmith.xyz>.\\nCopyright (c) 2018-2020 The lb contributors.\\nCopyright (c) 2020 R Nicolás Savinelli <rsavinelli@est.frba.utn.edu.ar>.\\n\\nUsage: blog-handler [OPTION]\\n\\n\
         blog-handler n:\\tnew draft\\n\
         blog-handler e:\\tedit draft\\n\
         blog-handler t:\\tdiscard draft\\n\
@@ -53,17 +54,17 @@ _newpost() {
 
 list() {
     printf "Listing contents of %s\\n" "$1"
-    case "$(ls -F "$1" | grep -v '[/@=|]$' | wc -l)" in
+    case "$(ls "$1" | wc -l)" in
         0) echo "There's nothing to list." && exit 1 ;;
-        *) ls -Frc "$1" | grep -v '[/@=|]$' | awk -F '/' '{print $NF}' | nl ;;
+        *) ls -rc "$1" | awk -F '/' '{print $NF}' | nl ;;
     esac
 }
 
 _listandPrompt() {
     local number="0"
     list "$1" "$2" && read -erp "Pick an entry by number to $2, or press Ctrl-C to cancel. " number
-    [[ "$number" -lt "1" ]] || [[ "$number" -gt "$(ls -F "$1" | grep -v '[/@=|]$' | wc -l)" ]] && echo "Error: There is no entry number $number." && exit 1
-    chosen="$(ls -Frc "$1" | grep -v '[/@=|]$' | nl | grep -w " $number" | awk '{print $2}')"
+    [[ "$number" -lt "1" ]] || [[ "$number" -gt "$(ls "$1" | wc -l)" ]] && echo "Error: There is no entry number $number." && exit 1
+    chosen="$(ls -rc "$1" | nl | grep -w " $number" | awk '{print $2}')"
     basefile="$(basename "$chosen")" && base="${basefile%.*}"
 }
 
@@ -75,9 +76,9 @@ _publish() {
     [ -z "$rssdate" ] && rssdate="$(LC_TIME=en_US date '+%a, %d %b %Y %H:%M:%S %z')" # RSS date formats must comply with standards to validate.
     webdate="$(date '+%a, %d %b %Y %H:%M:%S %z')" # But this visible date you can set to any format.
     tmpdir=$(mktemp -d)
-    printf "<!DOCTYPE html>\\n<html lang=\"en\">\\n<head>\\n<title>%s</title>\\n<link rel='stylesheet' type='text/css' href='%s'>\\n<meta charset='utf-8'/>\\n</head>\\n<body>\\n<h1>%s</h1>\\n<small>[<a href='%s#%s'>link</a>&mdash;<a href='%s'>standalone</a>]</small>\\n%s\\n<footer>by <strong><a href='%s'>%s</a></strong></footer>\\n</body>\\n\\n</html>" "$realname" "$css" "$realname" "../$blogfile" "$base" "$basefile" "$(cat "$webdir/blog/.drafts/$basefile")" "$website" "$name" > "$webdir/blog/$basefile"
+    printf "<!DOCTYPE html>\\n<html lang=\"en\">\\n<head>\\n<title>%s</title>\\n<link rel='stylesheet' type='text/css' href='%s'>\\n<meta charset='utf-8'/>\\n</head>\\n<body>\\n<h1>%s</h1>\\n<small>[<a href='%s#%s'>link</a> &mdash; <a href='%s'>standalone</a>]</small>\\n%s\\n<footer>by <strong><a href='%s'>%s</a></strong></footer>\\n</body>\\n\\n</html>" "$realname" "$standalonecss" "$realname" "../$blogfile" "$base" "$basefile" "$(cat "$webdir/blog/.drafts/$basefile")" "$website" "$name" > "$webdir/blog/$basefile"
     printf "\\n<item>\\n<title>%s</title>\\n<guid>%s%s#%s</guid>\\n<link>%sblog/%s</link>\\n<pubDate>%s</pubDate>\\n<description><![CDATA[\\n%s\\n]]></description>\\n</item>\\n\\n" "$realname" "$website" "$blogfile" "$base" "$website" "$basefile" "$rssdate" "$(cat "$webdir/blog/.drafts/$basefile")" >  "$tmpdir/rss"
-    printf "<div class='entry'>\\n<h2 id='%s'>%s</h2>\\n<small>[<a href='#%s'>link</a>&mdash;<a href='%s'>standalone</a>]</small>\\n%s\\n<small>%s</small>\\n</div>\\n" "$base" "$realname" "$base" "blog/$basefile" "$(cat "$webdir/blog/.drafts/$basefile")" "$webdate" > "$tmpdir/html"
+    printf "<div class='entry'>\\n<h2 id='%s'>%s</h2>\\n<p><small>[<a href='#%s'>link</a> &mdash; <a href='%s'>standalone</a>]</small></p>\\n%s\\n<small>%s</small>\\n</div>\\n" "$base" "$realname" "$base" "blog/$basefile" "$(cat "$webdir/blog/.drafts/$basefile")" "$webdate" > "$tmpdir/html"
     printf "<li>%s &ndash; <a href=\"blog/%s\">%s</a></li>\\n" "$(date '+%Y %b %d')" "$basefile" "$realname" > "$tmpdir/blogindex"
     printf "<li>%s &ndash; <a href=\"%s%s#%s\">%s</a></li>\\n" "$(date '+%Y %b %d')" "$website" "$blogfile" "$base" "$realname" > "$tmpdir/webindex"
     sed -i "/<!-- LB -->/r $tmpdir/html" "$blogfile"
