v1.2

diff --git a/nlb b/nlb
--- a/nlb
+++ b/nlb
@@ -1,7 +1,7 @@
 #!/bin/bash
 # nlb: blogs and rss feeds in about 100 lines of shell script.
 # https://github.com/rnsavinelli/nlb
-# nlb version: 1.1
+# nlb version: 1.2
 #
 # (c) 2018-2020 Luke Smith <luke@lukesmith.xyz>
 # (c) 2020 Savinelli Roberto Nicolás <rsavinelli@est.frba.utn.edu.ar>
@@ -11,7 +11,8 @@ webdir="$PWD"
 website="https://rnsavinelli.github.io/" # Keep a trailing slash.
 css="../css/stylesheet.css"
 blogfile="blog.html"
-indexfile="blogindex.html"
+blogindexfile="blogindex.html"
+websiteindexfile="index.html"
 rssfile="rss.xml"
 [ -z "$EDITOR" ] && EDITOR="vim"
 
@@ -27,7 +28,7 @@ fi
 
 _usageinfo() {
      printf \
-        "nlb v1.0 Blogs and RSS feeds in about 100 lines of shell script.\\nCopyright (c) 2020 R Nicolás Savinelli <rsavinelli@est.frba.utn.edu.ar>\\nCopyright (c) 2018-2020 Luke Smith <luke@lukesmith.xyz>\\n\\nUsage: nlb [OPTION]\\n\\n\
+        "nlb v1.2 Blogs and RSS feeds in about 100 lines of shell script.\\nCopyright (c) 2018-2020 Luke Smith <luke@lukesmith.xyz>\\nCopyright (c) 2020 R Nicolás Savinelli <rsavinelli@est.frba.utn.edu.ar>\\n\\nUsage: nlb [OPTION]\\n\\n\
         nlb n:\\tnew draft\\n\
         nlb e:\\tedit draft\\n\
         nlb t:\\tdiscard draft\\n\
@@ -58,9 +59,9 @@ list() {
 }
 
 _listandPrompt() {
-    local number="-1"
+    local number="0"
     list "$1" "$2" && read -erp "Pick an entry by number to $2, or press Ctrl-C to cancel. " number
-    [[ "$number" == "-1" ]] && exit 1
+    [[ "$number" -lt "1" ]] || [[ "$number" -gt "$(ls -F "$1" | grep -v '[/@=|]$' | wc -l)" ]] && echo "Error: There is no entry number $number." && exit 1
     chosen="$(ls -Frc "$1" | grep -v '[/@=|]$' | nl | grep -w "$number" | awk '{print $2}')"
     basefile="$(basename "$chosen")" && base="${basefile%.*}"
 }
@@ -79,7 +80,8 @@ _publish() {
     printf "<li>%s &ndash; <a href=\"blog/%s\">%s</a></li>\\n" "$(date '+%Y %b %d')" "$basefile" "$realname" > "$tmpdir/index"
     sed -i "/<!-- LB -->/r $tmpdir/html" "$blogfile"
     sed -i "/<!-- LB -->/r $tmpdir/rss" "$rssfile"
-    sed -i "/<!-- LB -->/r $tmpdir/index" "$indexfile"
+    sed -i "/<!-- LB -->/r $tmpdir/index" "$blogindexfile"
+    sed -i "/<!-- LB -->/r $tmpdir/index" "$websiteindexfile"
     sed -i "/ \"$base.html\"/d" "$webdir/blog/.htaccess"
     echo "AddDescription \"$realname\" \"$basefile\" #$rssdate" >> "$webdir/blog/.htaccess"
     rm -f "$webdir/blog/.drafts/$chosen"
@@ -92,14 +94,15 @@ confirm() {
 _delete() {
     sed -i "/<item/{:a;N;/<\\/item>/!ba};/#$base<\\/guid/d" "$rssfile"
     sed -i "/<div class='entry'>/{:a;N;/<\\/div>/!ba};/id='$base'/d" "$blogfile"
-    sed -i "/<li>.*<a href=\"blog\\/$base.html\">/d" "$indexfile"
+    sed -i "/<li>.*<a href=\"blog\\/$base.html\">/d" "$blogindexfile"
+    sed -i "/<li>.*<a href=\"blog\\/$base.html\">/d" "$websiteindexfile"
     rm -f "$webdir/blog/$basefile" && [[ "$1" != "draft" ]] && printf "Old blog entry removed.\\n"
 }
 
 _revise() {
     awk '/^<small>\[/{flag=1;next}/<footer>/{flag=0}flag' "$webdir/blog/$chosen" > "$webdir/blog/.drafts/$basefile"
     "$EDITOR" "$webdir/blog/.drafts/$basefile"
-    printf "Revision stored in blog/.drafts. Publish as normal entry when desired.\\n"
+    printf "Revision stored in %s. Publish as normal entry when desired.\\n" "$webdir/blog/.drafts/"
 }
 
 case "$1" in
